### ISSUE TITLE
Few things that may need correcting

### ISSUE THREAD

**Issue by Sweedify** [conan513/SingleCore_TC#11]
I've been following your stuff since forever and now I couldn't create an account in ac-web to come to you but here are couple small things that i think need to be fixed or added (in your own time IF even possible) -
1. Icecrown citadel gunship battle is impossible to solo, my idea would be to boost the damage output of the cannons, lower the health of the ships OR script the opposing factions ship to break when their boss is killed.
2. 1v1 (or the regular 2v2 3v3 5v5) arena for arenapoints, you think this could ever be possible?
3. Compile flying in azeroth for your next version, please!
4. in your latest release the custom pet npc is not working correctly, you can get a pet for yourself but when you change zones via teleporter the pet is gone and can't be summoned back.

Nonetheless a great project ! 

Thank you !

@conan513

**Comment by conan513** [comment]
Thanks for the review, but the npcbots and playerbots improvement is the most priority at the moment. If I found a patch for this then of course I add it in the next weekend.

**Comment by thesawolf** [comment]
@Sweedify (and @Conan513 just for information and linkage sake)
1. I haven't looked into this so no feedback, sorry.
2. LordPsyan has code in his repository for 1v1 Arena:
   His arena_template.patch is available: https://bitbucket.org/lordpsyan/lordpsyan-patches/raw/0bf4697ed7e066ec0297d97960404108755dd512/Individual/Included_in_All/2016_03_23-Arena_Template.patch (updated 23-03-2016)
   or his slightly older 1v1 Arena available: https://bitbucket.org/lordpsyan/lordpsyan-patches/raw/0bf4697ed7e066ec0297d97960404108755dd512/Individual/Included_in_All/2016_02_29-1v1ArenaFITTED.patch (updated 29-02-2016)
   **SIDENOTE**: I've used 1v1ArenaFITTED with recent TC and it works fine after some code adjustments.
3. Although there are objects that can enable you to fly in azeroth (kludgy but they work), a proper flying fix (with full use of mounts, etc.) seems to require dbc changes/updates and client-side mpq (with local dbcs). More info: http://www.ac-web.org/forums/showthread.php?218642-release-Working-World-flying-patch&highlight=azeroth+flying
4. I don't use the singlecore so I have no response to that one, sorry.

**Comment by conan513** [comment]
@thesawolf  can you compile your TrinityCoreLegacy on Windows?

I've got this:
http://pastebin.com/be3S8t9X

**Comment by thesawolf** [comment]
@conan513 I run my fork under Linux.. so no idea if it compiles under a window dev, I'm afraid.

**Comment by conan513** [comment]
Yeah under Linux it's working for me but no luck on Windows. I posted a pastebin link with the VS build log in another issue can you check it for me? Maybe you can help for me.
