### ISSUE TITLE
Compile - npcbots

### ISSUE THREAD

**Issue by skeezerbean** [conan513/SingleCore_TC#13]
Tried compiling your npcbots branch (you had asked on ac-web) in linux.
I had errors in compiling the enchant_visuals.cpp as it was including a config.h that didn't seem to exist. I'm not hardly a coder, all I could find was that CMAKE probably should be generating this file. The CMAKE command I ran was the same one I used for the TrinityCore. No errors when I ran it, but perhaps this branch needs something different or something needs updated.

If I renamed the enchant_visuals.cpp to .disabled, removed things from the build dir, then re-ran CMAKE - this is when I run into next when compiling

> In file included from /home/wow/SingleCore_TC/src/server/game/Entities/Object/Object.h:23:0,
>                  from /home/wow/SingleCore_TC/src/server/game/Maps/MapManager.h:22,
>                  from PrecompiledHeaders/gamePCH.h:4:
> /home/wow/SingleCore_TC/src/server/game/Entities/Object/Position.h: In member function âvoid blademaster_bot::blademaster_botAI::_calcIllusionPositions()â:
> /home/wow/SingleCore_TC/src/server/game/Entities/Object/Position.h:55:11: error: âfloat Position::m_orientationâ is private
>      float m_orientation;
>            ^
> /home/wow/SingleCore_TC/src/server/game/AI/NpcBots/bot_bm_ai.cpp:159:27: error: within this context
>              float o = me->m_orientation;
>                            ^
> In file included from /home/wow/SingleCore_TC/src/server/game/Entities/Object/Object.h:23:0,
>                  from /home/wow/SingleCore_TC/src/server/game/Maps/MapManager.h:22,
>                  from PrecompiledHeaders/gamePCH.h:4:
> /home/wow/SingleCore_TC/src/server/game/Entities/Object/Position.h:55:11: error: âfloat Position::m_orientationâ is private
>      float m_orientation;
>            ^
> /home/wow/SingleCore_TC/src/server/game/AI/NpcBots/bot_bm_ai.cpp:173:30: error: within this context
>                  _illusPos[i].m_orientation = o;
>                               ^

And also...

> src/server/game/CMakeFiles/game.dir/build.make:1227: recipe for target 'src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_bm_ai.cpp.o' failed
> make[2]: **\* [src/server/game/CMakeFiles/game.dir/AI/NpcBots/bot_bm_ai.cpp.o] Error 1
> make[2]: **\* Waiting for unfinished jobs....
> 
> CMakeFiles/Makefile2:1194: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
> make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
> make[1]: **\* Waiting for unfinished jobs....

**Comment by conan513** [comment]
I'm avoid that error but after no luck again
too many warning in playerbots files

**Comment by conan513** [comment]
http://pastebin.com/9dzR87fB

**Comment by skeezerbean** [comment]
Under linux this has the same problem as this and the link.txt file - [https://github.com/ike3/mangosbot/issues/71](https://github.com/ike3/mangosbot/issues/71)

After that is fixed the amount of warnings will drop when linking the worldserver.
