### ISSUE TITLE
Not getting the bots i set the conf to C:

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#14]
# Random bot count

AiPlayerbot.MinRandomBots = 1000
AiPlayerbot.MaxRandomBots = 1000
AiPlayerbot.RandomBotMinLevel = 1
AiPlayerbot.RandomBotMaxLevel = 80
I did the deletallaccounts set that to 1 restarted server and get only 450 bots, i did "rndbot reset" and "rndbot refresh"..?

**Comment by thesawolf** [comment]
Make sure your AiPlayerbot.RandomBotAccountCount  is high enough to compensate for 1000 bots.. If I'm not mistaken, I think it's 1 account for every 9-10 bots used in the bot chargen process.

**Comment by sout12** [comment]
Okay, i will try this now! Wow... it jumped from 450 bots to 898 :D thanksss!!
