### ISSUE TITLE
branch npcbots default DBs missing in source

### ISSUE THREAD

**Issue by skeezerbean** [conan513/SingleCore_TC#15]
In branch npcbots it needs the config files to somewhat match each other for database default settings.

Also, the source needs to have the blank auth/characters/world databases you want populated by default when starting with blank DBs. I didn't want to just copy over existing ones if the DB format had changed at all. Hopefully it hasn't because I'll try that next :P 

I did at least get it to compile in linux, I'll test and make sure it doesn't melt the core of the universe and then respond in detail.

**Comment by skeezerbean** [comment]
world server errors on startup, using a copy of the bots-lua version of DBs. I had to set the autoupdate for databases to 1. I assume there is a patch .sql I have to apply, I'll search in a moment.
[http://pastebin.com/i2hFcGb2](http://pastebin.com/i2hFcGb2)

(yes, I applied the patch .sql files and worldserver started. Now I don't know how to test... lol)

In this file -
src/server/game/Entities/Object/Position.h

I added the line for 'friend', to allow the errors previously in compiling to allow the blademaster class access this particular variable. I have no idea what type of effects this will cause, but I imagine that getting the orientation should be done another way but I can't find it in the code with my limited knowledge.

```
struct TC_GAME_API Position
{
    friend class blademaster_bot;
    Position(float x = 0, float y = 0, float z = 0, float o = 0)
```

There is still the problem inherited from mangosbot after running CMAKE in linux. You have to change the link order in this file - build\src\server\worldserver\CMakeFiles\worldserver.dir\link.txt

These 3 entries need to be in this order (libplugins moved after libgame)  _../scripts/libscripts.a ../game/libgame.a ../../plugins/libplugins.a_

**Comment by skeezerbean** [comment]
Is there any documentation on this? I at least was able to add an NPC into the world after doing .npcbot lookup, then .npcbot spawn based on one of the names. After that I should set owner to me and join the group.
However, it's still an NPC and not a player. I don't see a way to populate the world with a bunch of them as players if anyone wanted to do pvp, but sort of seems to work as a simple teammate. A bit of a pain to get them equipped as right now this level 20 warrior has a 2-handed axe which happens to be a forest mushroom... lol... ok then.

I hope this at least helps you get this compiled to test.

**Comment by thesawolf** [comment]
They are called NPCbots and not Playerbots for a reason :)  They are meant to be simple minions that follow you around and attack what you attack, etc. and that's about it (although the mage minion can give you food and water too). Normally, wherever you spawn them, they will return to that point when you are not in game. My friends tend to use them to fill a group out and run dungeons. They will PVP with you (if you have them enabled for pvp in settings). Don't expect much tho.. as mentioned, they are simpleminded and you can't TELL them to heal you, or attack a specific target.. that's what the Playerbots are for.

On a sidenote.. the NORMAL process for npcbots is to spawn one, set faction, invite them to join you, then group up with them. (although in my branch, I wrote in routine to autoset faction, tho I gave an option to change faction in gossip before inviting them.. also dismiss (remove from world) in that same gossip option).

Gear-wise.. normally the npcbots start out as level 80 and scales down to the spawner's level. You CAN gear them up.. but they tend to pre-populated with some gear, at least.

**Comment by skeezerbean** [comment]
Yes, definitely not playerbots ;)  It would be interesting to see this mixed with mangosbot. Like you said, filling out a raid to do a larger one would be interesting. I saw in their options that you could designate them to specific roles but I didn't test any of it.  Since they spawn as an NPC then I also could not inspect and had to rely on the speech menus. the one I had spawned and had dropped to my level (20) said he only had the forest mushroom.... as a weapon. :) 

If you're a coder at all do you know if it was 'safe' or good practice to handle the call to m_orientation as I did? Not sure what else to do, but otherwise it definitely would not compile in linux. I didn't bother trying compile in windows so might be the same error there.

**Comment by conan513** [comment]
you mean this is missing?
https://github.com/conan513/SingleCore_TC/tree/npcbots/sql/Patches/NPCBots

**Comment by skeezerbean** [comment]
The patch files were there, but in the event of a non-existing database then it asks if I want to create it and auto-populate. If I say yes then it errors that it cannot find the auth/character/world .SQL files to create the initial blank entries. I didn't capture the text, I just copied over existing DBs.

Does this at least help you get it to compile on your end? Hope this gets you to a point to tinker with it. :)

**Comment by conan513** [comment]
![ab605c17a533aa6473b3ed12f9a46a451](https://cloud.githubusercontent.com/assets/459246/16648187/1ab7ae0c-4433-11e6-9ff7-fde1cce7bfe7.png)

**Comment by thesawolf** [comment]
@conan513 You trying out some of my npcbot changes in my branch?
I'll be adding a better looking lookup routine later on (based on what I put together for playerbots.. haven't pushed it to repo yet since I'm fixing some things).
I probably should put up a readme on some of those changes.. tho you can see most of my code comments.
