### ISSUE TITLE
Not an issue just for Conans attention 

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#17]
Conan got to http://www.ac-web.org/forums/showthread.php?221383-Single-Player-Project-TC-R2/page19
A user named "Rym" has created a BG patch for the battleground Warsong, go to page 19 and look at it please :D

**Comment by conan513** [comment]
i know and test it soon

**Comment by sout12** [comment]
Awesome :D, is the Vbox release gonna be today or no?
