### ISSUE TITLE
Linux Vbox BG patch

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#20]
My BG patch on the Vbox version seems to not be working. I did the update command 3 times, i manually added the 2 new lines, idk what else to do 
![image](https://cloud.githubusercontent.com/assets/15899910/16753236/28605032-47b6-11e6-9948-eb11f678ef19.png)

**Comment by snomann72** [comment]
You added the lines correctly.  Did you shut down the server and restarted?  Once you do, and restart the worldserver, those 2 lines should disappear.  It took me a few tries to getting the lines to go away.

Also, the Bots do join BG (especially Warsong Gulch).  Tested it out already.

**Comment by sout12** [comment]
Oh im sorry this is old, i need to close this
