### ISSUE TITLE
SQL Errors in console when teleporting random bot

### ISSUE THREAD

**Issue by skeezerbean** [conan513/SingleCore_TC#23]
Linux, Ubuntu 16.04 using MySQL 5.7.12, fresh compiled from commit [https://github.com/conan513/SingleCore_TC/commit/d7b3b8689fd1ecc094f649dc677c2e308ba02847](https://github.com/conan513/SingleCore_TC/commit/d7b3b8689fd1ecc094f649dc677c2e308ba02847)

> Preparing location to random teleporting bot Iesm for level 53
> [1055] Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'world.c.map' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
> Unhandled MySQL errno 1055. Unexpected behaviour possible.
> Cannot teleport bot Iesm - no locations available

I remember seeing somewhere today about an SQL query being flagged but cannot remember where. I'm pretty sure it was dealing with teleportation issues with the playerbots so I am assuming this is related. Not sure what to do with it :)

Update - this is where I had seen it - [https://github.com/conan513/SingleCore_TC/commit/0c7d80a49b7e68210fc833ad4b304cc52aa1155e](https://github.com/conan513/SingleCore_TC/commit/0c7d80a49b7e68210fc833ad4b304cc52aa1155e)

**Comment by thesawolf** [comment]
I was talking with Conan about this one.. it might be MySQL specific as he is not seeing it on MariaDB atm.

**Comment by skeezerbean** [comment]
Possibly so, looks like there may be a config change needing to happen for MySQL.  That query anyway I think is massive, at that spot where it's sorting through maps and teleport locations many times will lock the CPU for many seconds while gathering/sorting info.  If I also read below correctly it may be best practices to form that particular query better anyways. But I don't know :D  Thanks for your help!

[https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html)

**Comment by skeezerbean** [comment]
This solved as far as the error goes. No idea about best practices :)

[https://www.sitepoint.com/quick-tip-how-to-permanently-change-sql-mode-in-mysql/](https://www.sitepoint.com/quick-tip-how-to-permanently-change-sql-mode-in-mysql/)

**Comment by thesawolf** [comment]
yeah.. I had alot of SQL stuff that broke due to deprecations when MySQL 5.7 came out :/ (not related to TC, just saying) Thanks for the info link. I still plan on going through that awful sql statement and making it compatible.

**Comment by skeezerbean** [comment]
If I remember right I think I had seen that in the code. It was some giant statement grabbing tons of level ranges from the DB, sorting, digging through away from water, sort some more, maybe go insane with sorting the whole database 4 times just for giggles, then teleport the bot somewhere weird underground ;)
