### ISSUE TITLE
Can't get the Vbox to work with hamachi i can port forward if i need to.

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#27]
Can you make the vbox work online with Hamachi? 
And yes, i did set my realmlist to my hamach Ipv4 ip.
I have port forwarded 
TCP 12975 (initiator port)
TCP 32976 (session port)

**Comment by conan513** [comment]
alright it's simpler than I think

first time you need to use the **gui** command
from the Application menu, start the **Terminal Emulator**
copy and paste this command into the terminal window:
**yaourt -S haguichi --noconfirm && sudo systemctl enable logmein-hamachi && sudo systemctl start logmein-hamachi**

after this command is asking few times of the 123456 password
when it's done, you can find the **Haguichi** app in **Applications/Internet** menu
start it and configure your hamachi settings

![asdasd](https://cloud.githubusercontent.com/assets/459246/16887184/d156b33c-4ad8-11e6-9ad6-0c87ab54a9a5.png)

after next restart it's connecting automatically, no need the gui and the Haguichi app again
maybe this will works for you too

![asdasd2](https://cloud.githubusercontent.com/assets/459246/16887230/04a294b8-4ad9-11e6-8aed-296522495af5.png)

**Comment by sout12** [comment]
https://i.gyazo.com/a7bc86caea228d45605e706b61a03661.png
Can't get it to work when i type the command :*(

**Comment by conan513** [comment]
Try this first:

sudo rm /var/lib/pacman/db.lck

Then

sudo pacman -Syu

And after this the command from above

**Comment by conan513** [comment]
This command updating the system first, maybe needed
