### ISSUE TITLE
AHBOT not buying many items

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#29]
My AHBOT seems to like buy one item. Like i put 20 stacks of Silk Cloth 1 gold each and it only bought 1 of them, how to fix ?

**Comment by thesawolf** [comment]
```
#
#    AuctionHouseBot.Buyer.Recheck.Interval
#       Description: This specifies the time interval (in minutes) between two evaluations of the same sold item.
#                    The smaller this value is, the more chances you give for an item to be bought by ahbot
#       Default:     20 (20min.)

AuctionHouseBot.Buyer.Recheck.Interval = 20
```

Try adjusting that to a smaller number.

**Comment by sout12** [comment]
I did, its at 1, for one minute 
AuctionHouseBot.Buyer.Recheck.Interval = 1

**Comment by thesawolf** [comment]
Then obviously the AHbot doesn't want your stinking extra 19 stacks of Silk Cloth :P 
You wanted personality in the bots.. there you go. (hehe)

But seriously.. the AHbot doesn't really like buying similar items back to back. I tend to sell stacks of enchanting components and spread them out throughout the day and they usually sell fine.. but drop them in bulk and meh. Plus. it's all about the pricing too.

**Comment by sout12** [comment]
Okay so, any item that i sell 2 of the AHBOT will buy one ? 
AuctionHouseBot.Buyer.ChanceMultiplier.Gray = 
What should all those values be set to or just keep them at 100?

**Comment by thesawolf** [comment]
Not saying that that is how it always goes. It's not ratio-based.. it's partly-random.. partly-"when's the last time I bought something from this player".. partly-pricing.. etc. Try dropping the price of the items and see if more sell. Who knows..

**Comment by sout12** [comment]
Okay then thanks for the clarification !

**Comment by sout12** [comment]
One more quesiton, the AHBOt only sells one type of arrows and bullets. Could i make it sell multiple types or no ?
And, what is the max amount of items can the AHBOT sell? Or is just like duplicates of the same item if you get to like 50k items.
