### ISSUE TITLE
possible Battleground solution

### ISSUE THREAD

**Issue by DuB1986** [conan513/SingleCore_TC#3]
While this is a singleplayer project, battlegrounds are missing from what I know.
It is still possible to spawn bots manuelly to battlegrounds and let them move around randomly
Is it possible if player joins battleground, all bots join battleground from the server (or lets say just 50)
automatically?
maybe they init=common(or rare) automatically to be the same level as the player?

**Comment by conan513** [comment]
if this is possible to do maybe ike3 can make it

**Comment by conan513** [comment]
A lua script added in the latest release where you can limits players and bots spawn area.
1. enable the restricted_zone script by removing the .disabled word from the name
2. edit the lines in this script

local ZoneCheck = {
        AllowedZones = {
                [12] = true,
        },
        TeleportLocations = {
                -- [TeamId] = {Map, X, Y, Z, Orientation}
                [0] = {0, -9468, 108, 58, 0},
                [1] = {0, -9410, 16, 60, 0},
        },

change the allowed zones ID to a battleground ID and the both spawn location
use the .gps GM command to get the coordinates

**Comment by DuB1986** [comment]
maybe you could take the code from dungeonfinder and let them join automatically and then roam around
this way the player can pvp without searchin for bots

**Comment by conan513** [comment]
rym bg patch silved this problem
