### ISSUE TITLE
Bot behavior in bg

### ISSUE THREAD

**Issue by Boxhead78** [conan513/SingleCore_TC#35]
Is it okay if I post here some bugs which have to do with the bots?

The bots often get stuck near the graveyard in warsong gulch.
They're fighting endlessly (or for a huge amount of time) like in the picture I uploaded below.
Is there a way for you guys to fix it?

![wowscrnshot_071816_201257](https://cloud.githubusercontent.com/assets/12766359/16925494/c5142296-4d24-11e6-9d57-a7cbe3b7b52f.jpg)

Besides that good work until now!

**Comment by nottah** [comment]
Camping the graveyard, very blizzlike :) I haven't experienced it yet myself.

**Comment by skeezerbean** [comment]
They tend to wait a few moments after a battle has stopped before moving on to their waypoints. Since during that time some more bots may resurrect, it starts all over again. Once it starts there isn't much of a way around it :)
