### ISSUE TITLE
seem to be having a problem with the vbox image.

### ISSUE THREAD

**Issue by nottah** [conan513/SingleCore_TC#37]
I have downloaded twice the files we had linked from Mega. I keep getting a corrupt image using 7zip and winrar. I am sure it is probably something on my end, but would like to know what program was used to decompress for the people who have a working image.

After the account hijacking fiasco, is the mega account still secure?

**Comment by conan513** [comment]
my mega is secured, but he can change all of my links on the forum.
I say do not download anything from there at now

https://mega.nz/#!us4BxDzI!uqHGTnTB48_2hAaBQFybPWolPqUIeiUicE9hc1-QwOw
https://mega.nz/#!39pSQCYL!v5Izm753qUhF8Y9vC2PU1iFXirC5xNEE2vDdd4xmkPs
https://mega.nz/#!n4hHCKrK!C1d8KQdf-1xzY9nJjV-RM23UDiAKO4axZf1ka8X3768
https://mega.nz/#!Tx4WXDhL!s_z2lJFWDUI-aic-q6AxuHPy0wXJPIJc8qXhvGHLLWg
https://mega.nz/#!DtgVjTAT!NM4e4YyEwGkTGRJkRriWYLV5tfYvkEBKg8RLrNpLfmQ
https://mega.nz/#!S5ABkTxC!jsmuS9h0UjQog_DPzTvC-DcK_zCDGxD34iRaBoNg30Q
https://mega.nz/#!2tJnDDKb!NqVLLNEFfp8WDtern_AAgS6pr5ICBvt-lNXDfkBpgl4
https://mega.nz/#!b5J3kBJR!kiApbYlHlTNXBKsrN-PS_UF9uOuzlhdsog2yagqfntE

here is the vbox parts link directly from mega

**Comment by nottah** [comment]
Thanks Conan, downloading and mirroring in my mega, since I know these are legit. I'll leave feedback in a little bit on whether it extracted proper this time. Do you start the extraction from the z01 file or the .zip file?

**Comment by conan513** [comment]
zip, I can extract it with default windows extractor and with winrar, maybe working with other extractors too like 7zip

**Comment by conan513** [comment]
but you need all parts to can extract it

**Comment by nottah** [comment]
works Great! I am now updating it using the update command. Seems very smooth.

As for the extracting, 7zip and my winrar seemed to have an issue, I used the built in windows extractor, and tried to drag it to the folder from the archive and it asked for the next volume. Then I just hit extract at the top of my explorer window and it worked flawlessly . The only issue, was it being OVF , I thought I could just import into my  VM Workstation 12. However it  gave a bunch of errors, so I installed the Virtualbox software and its smooth sailing. Thanks again , and keep updating! On a side note, the paypal, is it secure? Think I could spare a few bucks for the great work you are doing.

**Comment by conan513** [comment]
in my other treads looks like all link are fine
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VKANP262UFEUJ

there is some issue in the current vbox build, soon I will try to fix the dead bots issue

**Comment by nottah** [comment]
Donated and feel free to close my issue, thanks again.

**Comment by snomann72** [comment]
If you guys ever need a copy of the VBox Arch-SPP App, I have it on my system.  Downloaded way before the hax0rz every hacked conan's account.

BTW, the worldserver, auth and about everything in the Arch-SPP is now missing from the Virtualbox.  I am not sure if someone is updating the server or someone hacked the pull.

**Comment by nottah** [comment]
Hope its for an update, I had just recently pulled and updated and it seemed to make everything needed ,I did it must have been a couple hours ago. Seemed to work with no error. About to start up. I am sure one of the contributors will speak up.

**Comment by snomann72** [comment]
I just pulled the update about a hour ago, and the recent pull messed up the repack.  I had to re-add and going to reinstall the repack.  I made a clone of the current repack so if things go bad, I'll know.

**Comment by nottah** [comment]
I noticed that his account is unbanned over at ac-web (no Banned under name now), maybe we will find out soon.

**Comment by sout12** [comment]
@nottah Yep :D

**Comment by conan513** [comment]
On this weekend I will upload a new version of the vbox system

Fixing the "pacman in use" error and preinstall some program like hamachi. I'm trying to find a good CMS? (don't remember the name of the server manager site) and making a new update script to avoid the empty update.sh issue.

I want to avoid the console usage for regular users to make this more familiar. After the hijacking incident I'm not really want to keep alive the Windows release.

**Comment by sout12** [comment]
@conan513 As long as you can fix the hamachi bug and make it online, i am totally cool with you not keeping alive the Windows release. Less work for you meaning less time to get something done and more fun for us :D. You can focus on one thing now, i do think you should stop with the windows version actually. You also don't have to release a new repack every now and then for the updates, would be hella easier for you! Also, is the ghost bug happening on linux too if it is, have you figured out the problem? 
And, i can't seem to be able to get the BG patch to work on linux, i added the 2 new lines, idk what to do :(

**Comment by wrathix** [comment]
I prefer the vbox version already.  
Its really simple to get going, and when people actually take the few minutes to just give it a try, and find out that it's so easy to run, they will feel the same way.   Trying to keep two versions of it updated for people is too much work for you, as the vbox linux version is seriously all we need.

**Comment by sout12** [comment]
I just can't get the BG patch to work, its annoying :(
