### ISSUE TITLE
Initing a randombot

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#39]
Their is no way to init a randombot right? Their are bots they have no armor in BGS.
And, is their no way to like revive all dead players ?

**Comment by snomann72** [comment]
If it is the one that you do .npcbot lookup <class>, then nope.  There is no init command and there is no way of reviving dead npcbots.

**Comment by thesawolf** [comment]
I do not know about the randombots as I don't normally use them. I'll have to look and see if there is a .rndbot revive or something to that effect.

But to correct you, snoman, in the case of NPCBots.. yes.. there IS a revive command for those.
`.npcbot revive TARGET` -- revives selected npcbot. If player is selected, revives all npcbots of selected player)
- TARGET = selected npcbot OR npcbots OF selected player  
  Example Usage:  
  `.npcbot revive TARGET` (revives dead, selected npcbot or npcbots of selected player)

(the command is covered in my Bot Guide at: https://github.com/thesawolf/TrinityCore/blob/TrinityCoreLegacy/README_Bots.md 
if you don't have access to it, you would as a GM level account or may need to adjust RBAC permissions for the revive command)

**Comment by sout12** [comment]
@thesawolf One more quesiton, when you add a playerbot and you summon him and make him stay, does he join BGs too or no ?

**Comment by thesawolf** [comment]
I have no involvement regarding the bots and Rym's BG stuff, sorry. You'll have to ask Rym about that.

**Comment by sout12** [comment]
@thesawolf Is Conan's account on Acweb back? its not banned anymore
And Rym has been off the past few days :(

**Comment by snomann72** [comment]
The ones that you pay the bots, they do revive on their own.  I fell off a cliff and all 4 bots followed.  All of us died and they ran back to their bodies without using the revive command for npcbots.

**Comment by skeezerbean** [comment]
npcbot base diving ftw
