### ISSUE TITLE
Don't forget to add

### ISSUE THREAD

**Issue by N1k0VE** [conan513/SingleCore_TC#4]
Lordpsyan:
GuildLevelSystem.patch
NPCBuff.patch
npc-enchant.patch
ProfessionNPC.patch
BountyHunter.patch
LevelNPC.patch
LotteryNPC.patch
Pvp_ranks.patch
Played_time.patch
CongratsOnLevel.patch

**Comment by N1k0VE** [comment]
And maybe Jukebox by Rochet2 aswell :)

**Comment by conan513** [comment]
why you need GuildLevelSystem BountyHunter Pvp_ranks LevelNPC in an offline repack? :D

**Comment by N1k0VE** [comment]
Because I don't play it fully offline, but in a small group like max. 5 people. So we aren't always with 5 online. So it's kinda online/offline for me and that's why this is the best solution repack for this situation. ;). Bounty hunter and lotteryNPC aren't really neccesary.. but I guess it's not much work to add them. People don't need to use them if they don't want to.
