### ISSUE TITLE
Hire a npcbot at low levels?

### ISSUE THREAD

**Issue by oblisgr** [conan513/SingleCore_TC#40]
Is it possible to hire an npcbot at low level?
21g is bit difficult to aquire in level 10-30 for example.
I think the cost for hire a new npcbot could be scaled due player's level.
I dont know.. maybe there is such an option... but i havent found it.

**Comment by thesawolf** [comment]
It is scaled pricewise by your level. You can adjust the base cost in one of the conf files

```
#    NpcBot.Cost
#        Description: Bot recruitment cost (in copper).
#        Note: This value is for level 80 characters.
#              Cost is reduced for lower levels by simple formula: (cost * level / 80).
#        Default:   1000000 (100 gold, 1g25s at level 1)

NpcBot.Cost = 1000000
```

I guess I better update my guide to include the conf file settings.
