### ISSUE TITLE
Tank and healing bots

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#41]
Tank doesn't seem to always hold AOE
Healing bots seem to not always heal, they tend to want to do more damage than heal
![wowscrnshot_071916_190351](https://cloud.githubusercontent.com/assets/15899910/16969557/a1b53172-4de3-11e6-81b1-5e562aa804e0.jpg)
The bot here is doing the auto wand instead of healing

**Comment by thesawolf** [comment]
What is the point in that picture? I can't seem to see what that has to do with this issue you opened. It sounds like you need to adjust some strats. Make sure tank has co +tank, co +tank aoe, co +taunt. Make sure healer has co +heal and co -dps, co -dps aoe. 

And your statement "Tank doesn't seem to always hold AOE". AOE is not something you hold.. it's something you do and usually oriented towards dps. If you meant taunt, that's the way it is in real life, most times. Casters and even healers can get dps and heal aggro. It happens.

**Comment by sout12** [comment]
@thesawolf Well, the picture is just to show that the healer isn't healing but, these are randombots that i am playing with not playerbots. I will now on play with playerbots now.

**Comment by thesawolf** [comment]
Yeah.. hard to tell that from that picture :)

Yeah.. unfortunately, despite fixing some randombot segfaults early on, I don't have alot of experience with them, so I can't give any tips on what to do or not to do with them. You'd need some tips from others or Conan until I've had time to brush up on their commandsets. Good luck.

**Comment by sout12** [comment]
@thesawolf Sorry for the bad picture ^_^ thanks :D
