### ISSUE TITLE
Can't get the Vbox to work with the BG patch

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#43]
I can't get the bots to que for BGS
I added the lines i did the update command
https://embed.gyazo.com/1fb8e3e45d8ea6e19039bba8a2a7c82b.png

**Comment by Boxhead78** [comment]
Mine looks like this and it works.
https://i.gyazo.com/e32b7e8d7098733ba8507b530d7e0fb4.png

**Comment by sout12** [comment]
I put my bot.conf exactly like that, still no work. It only works on windows for me

**Comment by thesawolf** [comment]
First off.. please make sure to set NotSoRandom to 0 if you are using RandomBots. They work together.. but don't necessarily like each other. 
Secondly, I know this is a silly question to ask, but when you are making these changes to the conf.. you are fully stopping and restarting the worldserver, yes?

**Comment by sout12** [comment]
Yea i am
