### ISSUE TITLE
Anyway to disable not being able to init a alt character ?

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#46]
Im trying to .bot init=rare (Name) on my alt character on the same account but i can't, anyway to disable this?
Also, i can't add bots on other accounts that i made, could i disable this as well?

**Comment by thesawolf** [comment]
No. You aren't supposed to be able to use the playerbot alt feature to twink your alts. It is coded that way now not to allow init, random, updates anymore. The playerbot feature currently extends only to alts on your account and playerbots.. not toons on another legit account. Unless you change the coding, that's the way it's going to be. Sorry.

**Comment by sout12** [comment]
Oke, its fine just curious :D
