### ISSUE TITLE
NPCBot bug?

### ISSUE THREAD

**Issue by oblisgr** [conan513/SingleCore_TC#48]
I have set the conf settings like this to balance the bots to my player.

NpcBot.Mult.Damage.Melee = 0.5
NpcBot.Mult.Damage.Spell = 0.5
NpcBot.Mult.Healing      = 0.5

The damage created by spells is somehow like the damage I give in the same level, while the melee damage is too high. In the pic iI give you can see that the rogue npcbot (fighting with melee) gives too much damage, while the mage npcbot is too low. 

I have noticed that the average damage from melee attacks on level 28 is around 300!!!
While my player hits for max 70-80. Is this normal?
The spells casted by npcbots give about the same damage as my player.

![bug](https://cloud.githubusercontent.com/assets/9449831/17080700/ac0866c4-5141-11e6-9971-46c9686cea27.png)

**Comment by conan513** [comment]
ask this from https://github.com/thesawolf
