### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by talamortis** [conan513/SingleCore_TC#49]
This is not a bug, ive come across this and would like to test the core, i was wondering where could i find the database for this? thanks.

**Comment by thesawolf** [comment]
This uses the standard TC auto-populate database aside from various SQL inserts for some of the feature patches and addons and you can find those SQL inserts in SingleCore_TC/sql/custom 

There is no fully populated database  to download since it's generated at startup and updated from there.

**Comment by skeezerbean** [comment]
If you're missing the actual initial database file in the source then it can be downloaded from here - [https://github.com/TrinityCore/TrinityCore/releases](https://github.com/TrinityCore/TrinityCore/releases)

If that is needed then you'll see the message when starting the auth/world servers and when it asks if you want to create missing databases, then if you say yes it will error that it cannot find them.
