### ISSUE TITLE
Problem that all items get special stats

### ISSUE THREAD

**Issue by N1k0VE** [conan513/SingleCore_TC#5]
In your latest release, there's a problem that all items that you loot get special stats. Even items that you can't use like random drops of creatures. 
For example wool that drops got a +10 haste rating stat... ??
Please fix this or leave out the addon that does this.

**Comment by N1k0VE** [comment]
or is this a lua script I need to disable?

**Comment by conan513** [comment]
It's a lua script just remove it from the Scripts folder

**Comment by oblisgr** [comment]
And the name of the lua is.... ?
I find this really annoying too :P

**Comment by conan513** [comment]
PvE_Random_enchant_items.lua
