### ISSUE TITLE
feature request? Vbox Image

### ISSUE THREAD

**Issue by nottah** [conan513/SingleCore_TC#50]
Hope its ok to add this here!
Loving my vbox image, is there a way to slide in auto update check? Like when you log in it says update available?

The only reason I ask, is that I tend to update a bit frequently to keep it bleeding edge. However if there is no update, it still goes through the process of making clean and building. Takes a bit of time to finish considering there was no updates.

Or is there an option to use the update command and still be able to skip the rebuild process?

**Comment by conan513** [comment]
I'm working on a new update method, but the only way to check updates atm is here on github npcbots branch.
