### ISSUE TITLE
Latest update messing with World Server

### ISSUE THREAD

**Issue by CosmicRush** [conan513/SingleCore_TC#51]
I arrogantly thought on the ac-web forums that I had solved this, but lo and behold it's back again. Basically, to copy and paste from my post:
"I applied the newest update and am now having trouble with the world server.
Everything goes fine until:
"[1146] Table 'characters_ai_playerbot_locks' doesn't exist.
Your database structure is not up to date. Please make sure you've executed all queries in the /sql/updates folder."

Here's the problem. I executed the update fine without any problems, and I'm looking at characters_ai_playerbot_locks right now (It totally exists)."

After that message, the world server crashes. I've tried manually dragging and dropping the mentioned files into their proper places, and even double-checked to see if the update applied them right(there were no warning messages), but still no positive results. I'm willing to participate in being a guinea pig if somebody could lend a hand.

**Comment by wimboehme** [comment]
You can fix it by manually applying the script in the file 2016_07_12_ai_playerbot_locks.sql.
I had that yesterday myself and fixed it by applying that script using MySQL workbench to connect to the server.

**Comment by CosmicRush** [comment]
Thank you so much for the reply, but unfortunately I'm rather new to MySQL and have no idea what I'm doing. Could you explain it to me like one would explain to a cross-eyed turtle?

On a project-related note, any idea what's causing this if it's happening to more than one person?

**Comment by wimboehme** [comment]
They propably forgot the script in the update script or some bug prevents it from executing.

You can download the Mysql Workbench here: https://dev.mysql.com/downloads/workbench/5.2.html
Once it's installed you need to add a connection to the database server. The settings can be seen when you launch the update.bat file.

Once connected you need to select the character database, copy paste the text from the sql file and execute it.
