### ISSUE TITLE
Ranged bots

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#54]
Ranged bots tend to just stand their when a target is very close to them.

**Comment by thesawolf** [comment]
You should probably be a little more specific. NPCBot, PlayerBot, RandomBot?
If it's PlayerBots, you'd need to make sure they have other strats included to help them determine what to do (ie. co +kite)
Also, I know you are big into the BG's.. is this BG only behaviour or regular game?

If you are going to post an issue, please provide more details.

**Comment by sout12** [comment]
Sorry for not providing details, this is a randombot in a BG. I think Rym has already confirmed that will get in range so, nvm about this.
