### ISSUE TITLE
Disabling custom content/patches and missing profession

### ISSUE THREAD

**Issue by CosmicRush** [conan513/SingleCore_TC#6]
As it stands, it would seem that there is no way to disable such things like auto-learning skills on level up, lordpsyan's city NPCs, and various other tidbits. There are some things that can be disabled via the world.conf file, but those are rather few in comparison to the things added.

I understand that the SPP needs certain things in order to be functional as a, well, single player project, but the option to pick and choose which custom server options can be activated and deactivated would be nice.

Also, Jewelcrafting is nowhere to be found in the game apart from the kit. Even the trainers and option to ask where the trainers reside are missing.

**Comment by conan513** [comment]
Lots of LordPsyan's patch are hardcoded and can't be disabled with a simple on/off option.
You need to request this from LordPsyan.

I check the jewelcrafting stuff soon.

**Comment by conan513** [comment]
https://github.com/conan513/SingleCore_TC/commit/f4e9568325ddb0600d2bd993bc55f43539298d98
https://github.com/conan513/SingleCore_TC/commit/6d438e62cb00a4fd7767eb4bb1262332b3e18524

ok auto learn now can be disabled

**Comment by CosmicRush** [comment]
As per usual, you're a God. Or at least a Demi-god. Nonetheless, thank you Conan. Although this was more of a matter of personal preference (barring the Jewelry), I'll try to report any more bugs I come across.

EDIT: Sorry to bring this up, but I have no idea on how to work with C++/technologically retarded. I've added the script, but I don't know what to do with the other file.

**Comment by conan513** [comment]
wait for the next release (maybe the final)
I'm trying to find an alternative lua script for some patches to can be enable/disable it

**Comment by CosmicRush** [comment]
Ah, okay. Thank you.

**Comment by conan513** [comment]
Ok it's released 
check on a web

**Comment by sout12** [comment]
Conan man, i hope u get donated frequently, ur such a hard worker like forreal !
