### ISSUE TITLE
A few bugs (some new and some old)

### ISSUE THREAD

**Issue by snomann72** [conan513/SingleCore_TC#63]
I posted this over at the other site, so I'm posting the info here.

Found a few minor DB issues, and not sure if you're aware of it.  Like this one.

[Condition SourceType: 15 (Gossip Menu Option), SourceGroup: 50000, SourceEntry: 1, ConditionType: 6 (Team)] specifies unknown team (0), skipped.
[Condition SourceType: 14 (Gossip Menu), SourceGroup: 50000, SourceEntry: 300001] GossipMenu 50000 not found.
[Condition SourceType: 14 (Gossip Menu), SourceGroup: 50000, SourceEntry: 300001] Not handled grouped condition.
[Condition SourceType: 14 (Gossip Menu), SourceGroup: 50000, SourceEntry: 300000] GossipMenu 50000 not found.
[Condition SourceType: 14 (Gossip Menu), SourceGroup: 50000, SourceEntry: 300000] Not handled grouped condition.

Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Player::LoadFromDB: Player (GUID Full: 0x000000000000182d Type: Player Low: 6189) tried to login while forced to rename, can't load.'

The spell 34453 (rank: 1, first: 34453) listed in `spell_ranks` already has ChainEntry from dbc.
The spell 34454 (rank: 2, first: 34453) listed in `spell_ranks` already has ChainEntry from dbc

Item (Entry: 60000) does not exist in item.dbc! (not correct id?).
Item (Entry: 60001) does not exist in item.dbc! (not correct id?).
Item (Entry: 60002) does not exist in item.dbc! (not correct id?).
Item (Entry: 60003) does not exist in item.dbc! (not correct id?).
Item (Entry: 60004) does not exist in item.dbc! (not correct id?).
Item (Entry: 60005) does not exist in item.dbc! (not correct id?).
Item (Entry: 60006) does not exist in item.dbc! (not correct id?).
Item (Entry: 60007) does not exist in item.dbc! (not correct id?).
Item (Entry: 60008) does not exist in item.dbc! (not correct id?).

SmartScript: Action target Creature (GUID: 45218 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 45218 Entry: 5743) skipped to prevent crash.

InitSpellMap(): No SpellInfo found for base spell 0

Been seeing alot of these issues since a few updates back.  And Conan, when will you update the momcat script?

**Comment by thesawolf** [comment]
momcat is my creation. I abandoned it in favour of a graphical lookup instead of an item-based lookup. It can be removed/ignored.

**Comment by snomann72** [comment]
How do I go about removing the momcat script?  I rather remove it than letting it hang in the bootup.  The less errors for the loadup, the better, imho.

**Comment by conan513** [comment]
umm if you enable debug infos then you see a tons of error on loadup :)
these errors are not real errors, if the server running in a real error then crashing immediately

**Comment by snomann72** [comment]
Been getting some major crash issues, especially with Molten Core.  The last boss is not spawning after downing all the other bosses.  Got to the mini-boss where you kill his adds and he talks about going to the end boss.  He never shows up and I had to summon him manually.

Also, didn't mess with any debug info thing.  Not sure where that is to disable it.

The one error I been getting is Player::LoadFromDB: Player (GUID Full: 0x000000000000182d Type: Player Low: 6189) tried to login while forced to rename, can't load.' and it is constant.  Don't know which player it is.  I might have to look into the DB and see which one it is.

**Comment by thesawolf** [comment]
Please be aware that content issues are usually something that has to be added/scripted by the TC team. As for the momcat, you need to remove the script calls in the loader files too. I'll see about removing it in upcoming commit if Conan happens to grab it. And "less errors", in this case, is moot. It's not an issue or an error causing any kinds of problems aside from an entry in the logs.
