### ISSUE TITLE
Error #134 with Creating Blood Elf Class

### ISSUE THREAD

**Issue by snomann72** [conan513/SingleCore_TC#65]
I posted a issue on the AC-Web but have not heard anything back.  I reset everything (Server, etc...).  When creating a new character, I get Error #134.  Had a issue when running both 3.3.5a and 7.x, so started fresh.

I am thinking that when the server was updated to the latest revision for 3.3.5a, it broke one of the files.  Here is the info I received from creating a Blood Elf.  The BLP file looks like from the server side.

ERROR #134 (0x85100086) Fatal Condition
Program:    D:\WoW\World of Warcraft 3.3.5a (no install)\Wow.exe

Failed to read file DUNGEONS\TEXTURES\SILVERMOONCITY\BLDELF_WINDOWBTM. blp

Debug Info:

[2] err=0 text=SFileReadFile - DUNGEONS\TEXTURES\SILVERMOONCITY\BLDELF_WINDOWBTM. blp - Data\patch.MPQ
[1] err=0 text=ReadSectors/DecompressData failed
[0] err=0 text=ReadSectors/DecompressData failed

UPDATE:  I re-installed everything and re-setup everything and the Error #134 on the client side is fixed now.  The error, as I mentioned, has something to do with that BLP file which not sure how that happened.

**Comment by conan513** [comment]
belf working fine for me
no any issue with character creation

**Comment by snomann72** [comment]
Here is the error log on pastebin.  You can see it was that file.  Not sure why it happened tho.  When I redone the server, the Error  Code 134 went away.

http://pastebin.com/FhkuaMhv

**Comment by talamortis** [comment]
looks like the fault is your wow client mate. well i would say it it it cant find the textures for Blood elfs

**Comment by snomann72** [comment]
Ya, that is what I was thinking.  Haven't really had any issues with any error codes til now.  I am thinking it was a problem with the update.  When I redone the server and update, that issue went away.
