### ISSUE TITLE
WorldServer crashes from time to time

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#7]
Log: http://pastebin.com/6DSgCGeJ

**Comment by conan513** [comment]
Send me the logs too

**Comment by sout12** [comment]
Got another crash
2nd Log: http://pastebin.com/K2LVqGJp

**Comment by conan513** [comment]
Server.log and database.log needed

**Comment by sout12** [comment]
Oh, im sorry C: 
Server log : http://pastebin.com/C2a6fSzT
Database log : http://pastebin.com/qTR252vJ

**Comment by conan513** [comment]
Hmm doesn't seem anything strange
Send me the server and database logs right after a crash and don't start it again

**Comment by sout12** [comment]
That log was after a crash, and i didn't start it again, but i will send u logs after it crashes if it does without restarting it

**Comment by sout12** [comment]
It just crashed, heres logs
Server: http://pastebin.com/T0XMCSzq
Database: http://pastebin.com/u8fnWpP5
All what i did was in worldserver i typed "Rndbot refresh" idk if that made it crash or what...?

**Comment by conan513** [comment]
Yeah maybe a high database request do that crash

I check your log again when I'm home
