### ISSUE TITLE
Build Fail on Linux and Windows

### ISSUE THREAD

**Issue by BlackWolfDEsign** [conan513/SingleCore_TC#77]
`In file included from ~/Core/src/server/game/LuaEngine/LuaEngine.cpp:14:0:
~/Core/src/server/game/LuaEngine/ElunaCreatureAI.h:144:10: error: ‘void ElunaCreatureAI::AttackedBy(Unit*)’ marked ‘override’, but does not override
     void AttackedBy(Unit* attacker) override
          ^~~~~~~~~~
~/Core/src/server/game/LuaEngine/ElunaCreatureAI.h: In member function ‘void ElunaCreatureAI::AttackedBy(Unit*)’:
~/Core/src/server/game/LuaEngine/ElunaCreatureAI.h:147:13: error: ‘AttackedBy’ is not a member of ‘ScriptedAI’
             ScriptedAI::AttackedBy(attacker);
             ^~~~~~~~~~
src/server/game/CMakeFiles/game.dir/build.make:3758: recipe for target 'src/server/game/CMakeFiles/game.dir/LuaEngine/LuaEngine.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/LuaEngine/LuaEngine.cpp.o] Error 1
CMakeFiles/Makefile2:1396: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@Ubuntu-1610-yakkety-64-mi`

compile error 

**Branch**:
wotlk-reworked

**Operating system**:  
Linux and Windows

**Comment by conan513** [comment]
yup, currently I'm waiting for rochet2 to upgrade the eluna core
roll back the latest TC pull if you want to compile

**Comment by BlackWolfDEsign** [comment]
thx you for this information :)
