### ISSUE TITLE
VMap file 'Data/vmaps/000.vmtree' couldn't be loaded

### ISSUE THREAD

**Issue by electricmessiah** [conan513/SingleCore_TC#78]
**Description**:
After compiling this build, the world.exe fails with a vmap error. I rebuilt the vmaps, just for fun, but it produces the same error. Reverting to the npcbots branch works with no issues.

**Current behaviour**: Tell us what happens
VMap file 'Data/vmaps/000.vmtree' couldn't be loaded
This is because the version of the VMap file and the version of this module are
different, please re-extract the maps with the tools compiled with this module.
Unable to load critical files - server shutting down !!!

**Branch(es)**: 335/6x  
worlk-reworked

**Operating system**:  
VMWare Win 7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by conan513** [comment]
you need to use the fresh compiled tools to extract maps vmaps etc

**Comment by electricmessiah** [comment]
Where are these fresh compiled tools at? They are not built when compiling this branch.
