### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#8]
How do u get into the source so that i can edit the amount of bots that are in a guild from 20 to like 200 or something?

**Comment by conan513** [comment]
search for this in visual studio:
if (guild->GetMemberCount() < 20) 

then recompile the server

**Comment by sout12** [comment]
Okay, i will try this when i get home later i am not very good at this whole source thing but i will try

**Comment by sout12** [comment]
I am a bit confused on what to do here, could you give more of an advanced step by step process ?
Which visual studio do i download? Could you like send me a link for all what i did please?

**Comment by conan513** [comment]
trinitycore wiki?
