### ISSUE TITLE
Connection_patcher : Unable to find pattern

### ISSUE THREAD

**Issue by bifidus** [conan513/SingleCore_TC#90]
**Description:**

When I start connection_patcher to patche the client, I have the following error : Unable to find pattern.

**Current behaviour:**

![sans titre](https://user-images.githubusercontent.com/42901451/44958206-206fbf80-aedd-11e8-8fa1-53b909e06249.jpg)

**Expected behaviour:**

Patched successfully

**Project(s): <-- Mandatory**

- [ ] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

https://github.com/conan513/SingleCore_TC

**Database version**

MariaDB 10.1.30

**Operating system:** 

Windows 7 Professional 64 bits

**Comment by DJBoxer** [comment]
Try placing exe and patcher in folder on its own, then drag exe onto patcher. Or its already patched

**Comment by bifidus** [comment]
I try placing exe and patcher in folder and drag exe into patcher but same issue. I think the .exe is already patched but not sure. I try with other .exe and same issue.
